---

# Apply calico cni to the cluster
- name: Copy calico.yaml file in /tmp
  copy:
    src: calico.yaml
    dest: /tmp/calico.yaml

- name: Apply calico cni
  command: kubectl apply -f /tmp/calico.yaml

# Install k9s
- name: Download k9s binary
  get_url:
    url: "https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz"
    dest: "/tmp/k9s_Linux_x86_64.tar.gz"

- name: Extract k9s archive
  unarchive:
    src: "/tmp/k9s_Linux_x86_64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    creates: "/usr/local/bin/k9s"

- name: Make k9s executable
  file:
    path: "/usr/local/bin/k9s"
    mode: "+x"

...

